language: cpp
sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - libjemalloc-dev
      - libboost-dev

before_install:
  # install updated version of cmake
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-rc3-Linux-x86_64.sh
  - sh cmake-3.3.0-rc3-Linux-x86_64.sh --prefix=$HOME --exclude-subdir

  # use g++-4.9 if g++ is our compiler
  - export CXX=g++-4.9

script:
  # Ensure accurate version of CMake and GCC
  - cmake --version
  - gcc --version
  - cmake -Dtest=ON . && make && ./unit_tests