language: cpp
sudo: yes

before_install:
  - sudo apt-get install libjemalloc-dev
  - sudo apt-get install libboost-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudp apt-get upgrade

script:
  - cmake --version
  - cmake -Dtest=ON . && make && ./unit_tests