language: cpp
sudo: yes

before_install:
  - sudo apt-get install libjemalloc-dev
  - sudo apt-get install libboost-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-rc3.tar.gz
  - tar -xvf cmake-3.3.0-rc3.tar.gz
  - cd cmake-3.3.0-rc3
  - cmake . && make && sudo make install

script:
  - cmake --version
  - cmake -Dtest=ON . && make && ./unit_tests